remote_theme: "mmistakes/minimal-mistakes@4.24.0"

title: Stephen Swires
locale: en-GB
description: My personal website.
url: https://swires.me

permalink: /:year/:month/:title
show_excerpts: true

plugins:
  - jekyll-include-cache

# Theme settings
minimal_mistakes_skin: "air"
subtitle: "Game Developer, Programmer"
include: ["_pages"]
author:
  name: "Stephen Swires"
  bio: "Game Developer, Programmer. Currently Associate Tech Director @ Blackbird Interactive."
  avatar: "/assets/images/avatar.jpg"
  location: "Calgary, AB, Canada"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/sswires89"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/stephen-swires/"

footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:steve+website@swires.me"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/sswires89"
    - label: "Bluesky"
      icon: "fas fa-fw fa-square bsky"
      url: "https://bsky.app/profile/swires.me"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/stephen-swires/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      show_date: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      show_date: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/


# Hide the maintained by line
github.is_project_page: false
